{{- if .Values.staticPersistentVolume -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storageClassName | default .Release.Name }}
  gcePersistentDisk:
    pdName: {{ .Values.gcePersistentDiskName | default .Release.Name }}
    fsType: ext4
{{- end }}
